pages:
  stage: deploy
  script:
    - mkdir .site
    
    - cp index.html .site/
    
    - cp -r public .site/
    
    - rm -rf public
    
    - mv .site public
  artifacts:
    paths:
      - public
  only:
    - main